//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crescent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int ID { get; set; }
        public string DocID { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string Source { get; set; }
        public string Content { get; set; }
        public string Phone { get; set; }
        public string Misc { get; set; }
        public string Person { get; set; }
        public string Location { get; set; }
        public string Organisation { get; set; }
        public string Money { get; set; }
    }
}
