//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crescent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lookUp_Master
    {
        public int ID { get; set; }
        public Nullable<int> Level1ID { get; set; }
        public Nullable<int> Level2ID { get; set; }
        public string NameOflookUp { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
